### ISSUE TITLE
KeyError: 'mediainfo'

### ISSUE THREAD

**Issue by samcro1967** [ilarramendi/BetterCovers#2]
The container starts and processes a few movies and then I get the error below 29 times in a row.  it causes the container to restart and then it processes a few more movies properly until it happens again. 

```
today at 9:49:08 AM Exception in thread Thread-3390:
today at 9:49:08 AM Traceback (most recent call last):
today at 9:49:08 AM  File "threading.py", line 917, in _bootstrap_inner
today at 9:49:08 AM  File "threading.py", line 865, in run
today at 9:49:08 AM  File "BetterCovers.py", line 114, in processFolder
today at 9:49:08 AM  File "BetterCovers.py", line 35, in generateTasks
today at 9:49:08 AM KeyError: 'mediainfo'
```

**Comment by ilarramendi** [comment]
Helo! Sorry for not answering, can you try updating the container or repository and all BetterCovers files and try again?
