### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by samcro1967** [ilarramendi/BetterCovers#3]
@ilarramendi The current docker image has 361 High and Critical security vulnerabilities.  Updating the image will reduce it to 32 that either do not currently have fixes or will not be fixed if you are still maintaining this project.  Great project and appreciate your work!

**Comment by ilarramendi** [comment]
Just updated it and managed to get it down to 116, if you have any other suggestion its appreciated

**Comment by samcro1967** [comment]
Huge improvement.  I am guessing that is 116 total High and Critical security vulnerabilities.  I am now running local Gitea, Drone, Runner, and Docker registry instances.  I clone your repo locally every night locally (to pick up any new code changes) and build the image to get the latest security updates.  I also run grype nightly against all containers only showing high and critical security vulnerabilities that have fixes available.  I don't capture security vulnerabilities without fixes.  Don't see the point as there is not much you can do about them until fixe are available.  I  am only showing 1 fix at this point in time that was not in my build early this morning.

Appreciate all of your work.  Great product!
